<h1>Working with COVID-19 Data from Johns Hopkins</h1>
<p>The following data is taken from Johns Hopkins University.The object is to iterate through all files in the /confirmed directory and create a pandas dataframe that captures all the data in each file in one table</p>
<p>Ref: https://github.com/CSSEGISandData/COVID-19</p>

In [1]:
# Dependencies
import pandas as pd
import glob

In [4]:
# Use glob to open each file and store the data in a pandas df
path = r'C:\Users\mjgri\Programming\cs106a\confirmed'
all_files = glob.glob(path + '/*.txt')

# Create empty list to populate with all data from all files
li = []

# Iterate through each file and store the data in to a pandas dataframe
for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

# Concatenate each of the dataframes/files into one dataframe
frame = pd.concat(li, axis=0, ignore_index=True)

# Print the dataframe
frame

          0   2   1
0       0.0 NaN NaN
1       0.0 NaN NaN
2       0.0 NaN NaN
3       0.0 NaN NaN
4       0.0 NaN NaN
...     ...  ..  ..
19651  34.0 NaN NaN
19652  34.0 NaN NaN
19653  34.0 NaN NaN
19654  34.0 NaN NaN
19655  35.0 NaN NaN

[19656 rows x 3 columns]